### ISSUE TITLE
make the progress bar window half in height

### ISSUE THREAD

**Issue by Sopor-** [jwensley2/DownloadStatusBar#2]
Could you make the progress bar window half in height, maybe as an option? I understand it won't fit so much info but i can always hover the mouse pointer over it to get full info.

**Comment by jwensley2** [comment]
You can hide the status and/or progress text lines in the addon options, which will make the bar smaller.

![image](https://user-images.githubusercontent.com/379479/33518822-8e014af6-d769-11e7-8f90-fa79d27865ca.png)

**Comment by Sopor-** [comment]
Yes, that was much better but now it is a bit too wide... Do it need to be that wide?

If i paste in a URL (that will immediately start) in an empty tab i get no progress bar. I have to change to another tab for it to show up.

**Comment by jwensley2** [comment]
> Yes, that was much better but now it is a bit too wide... Do it need to be that wide?

It should fit to the width of the text but there is a min/max, I can play around with the minimum width a bit though.

> If i paste in a URL (that will immediately start) in an empty tab i get no progress bar. I have to change to another tab for it to show up.

Because I have to inject HTML into the page to show the status bar there are some limits on where it can be shown, like not on https://addons.mozilla.org or in new or empty tabs.

Hopefully Mozilla will add a status bar API in the future that will make it possible to show it everywhere.
