### ISSUE TITLE
A few Issues for version 1.7.5 with Firefox 59.0.1 64 bit

### ISSUE THREAD

**Issue by gkdiamond** [jwensley2/DownloadStatusBar#65]
The sound does not work for short downloads only longer ones.

The download status bar only show in the window that the download was started in instead of all open tabs and windows (including popup windows or new tabs while the download is in progress).

The progress is not updated when it is being viewed in the popup status window.

**Comment by jwensley2** [comment]
> The sound does not work for short downloads only longer ones.

This is intended, I didn't want the sound being spammed when someone downloads a bunch of small files. It plays if the downloads takes more than 1 second.

> The download status bar only show in the window that the download was started in instead of all open tabs and windows (including popup windows or new tabs while the download is in progress).

I can't reproduce this, I see the bar in all regular tabs in all windows. There are a few places it cannot be shown though.
- addons.mozilla.org, because of security restrictions
- new tabs (about:newtab), also because of security restrictions it seems

> The progress is not updated when it is being viewed in the popup status window.

I assume you mean the tooltip when you hover over a download? I do know about that, but I haven't gotten around to fixing it yet.

**Comment by gkdiamond** [comment]
Thanks for the follow up and so quickly. You are right, I see the download bar in all windows now. I do not know why I could not before, maybe just closing Firefox and opening it sorted it out. Thanks.
