### ISSUE TITLE
clear button still won't work

### ISSUE THREAD

**Issue by Sopor-** [jwensley2/DownloadStatusBar#7]
The big Clear button to the left still won't clear finished and canceled downloads.

**Comment by jwensley2** [comment]
I'm not able to reproduce this, are you using 1.5.2? It clears complete and cancelled downloads for me.

**Comment by Sopor-** [comment]
It seems to happen when a download fails to download. If the file only gets downloaded to 90% (server error).
I have tried to simulate a failure but without any success. Let me know if this information is enough or i will try to reproduce it again.

**Comment by Sopor-** [comment]
I manage to find the file again but beware of the file because i have now idea what it is...
![image](https://user-images.githubusercontent.com/5789283/33637215-f09dc6e0-da1f-11e7-8041-a6c0bd7dcb89.png)
At this point the Clear button won't work.

**Comment by jwensley2** [comment]
Okay, so I think what you are seeing is intended behaviour. When I tested this it removed the completed and normally cancelled downloads, but not the failed ones.

If a download fails at 99.9% someone and gets cleared with some completed downloads someone might be left wondering why their download isn't done.

I think if I changed failed downloads to be red or something then it might make more more sense to have the clear button also clear them because it would be obvious that it had failed.

**Comment by Sopor-** [comment]
Yes, change the color to red would be great, but please make the clear button work and the auto clear when i have fixed the error. If i have many files that have failed to download one cancel press is enough. I don't want to clear them all too.
